---
deployment:
  tasks:
    # Ganti "nama-folder-tema-anda" dengan nama folder tema yang benar di cPanel
    - export DEPLOYPATH=/home/ambrawar/public_html/wp-content/themes/KINGLAB/
    - /bin/cp -R * $DEPLOYPATH
